Migrate test framework to Hardhat
JoinColony/colonyNetwork pull request #1196
Opened 2024-01-05 15:28 UTC by kronosapiens

Initial drop-in migration using an external RPC node for testing

2024-03-11 19:02 UTC, kronosapiens commented
Noting that the latest version of hardhat (2.21) introduced a new dependency: @nomicfoundation/edr which seems to break our build. So pinning to version 2.19 with a tilde for now.

2024-03-12 17:01 UTC, kronosapiens commented
Noting also that the version check script may need to be migrated over. It is passing now but this may be a false negative.

2024-03-15 21:53 UTC, kronosapiens commented on test/cross-chain/cross-chain.js
> -    // Get the etherrouter address
I don't actually remember why this was removed

2024-03-19 11:22 UTC, area requested changes
Looking really good, overall!

* You have `cross-chain` listed as "Not running" in the PR, is that a mistake, or am I missing something?
* Is there something fundamentally broken with the version checking (as is the case for the smoke tests), or is it just something you've not got to?

2024-03-19 20:38 UTC, kronosapiens commented on package.json
> +    "test:reputation:1": "npm run start:blockchain:client && nyc npx hardhat test ./test/reputation-system/*.js --network development",
Not sure. The only two times we reference `nyc` is `test:reputation:1` and `test:reputation:2`.

2024-03-19 20:40 UTC, kronosapiens commented on packages/kyc-oracle/KycOracle.js
> +    const flags = { abi: true, address: false };
Seems like they already are

https://github.com/JoinColony/colonyNetwork/blob/develop/packages/package-utils/TruffleLoader.js#L5

2024-03-19 20:44 UTC, kronosapiens commented on package.json
> +    "test:reputation:1": "npm run start:blockchain:client && nyc npx hardhat test ./test/reputation-system/*.js --network development",
Might we be able to ditch `nyc` entirely?

2024-03-19 20:49 UTC, kronosapiens commented on contracts/testHelpers/TestExtensions.sol
> -// SPDX-License-Identifier: GPL-3.0-or-later
I'm pretty sure it has to do with having to pass the test extensions through `setupEtherRouter`, which makes some assumptions about contract paths. The `ColonyNetworkAuction` contract contains two contracts, but the second one (`DutchAuction`) is not an `EtherRouter` and so those assumptions are not relevant.

2024-03-19 20:56 UTC, kronosapiens commented
Regarding the version check script, I'm not 100% sure. Given that the "last release" will run on truffle and the "current" version will run on hardhat we may need to update that file a few times over the next release cycle to keep the commands / paths accurate. I can keep working on it, but I'm also happy just saying that it won't work for releases which span truffle/hardhat.

2024-03-22 14:35 UTC, area commented
Consider this approval, but with provisos:

* I'd like #1227 to be reviewed and merged first, as it's the sort of PR that the storage tests (disabled here) are intended to give confidence in.
* Not a fan of the renamed `TRUFFLE_FOREIGN`. The name was intended to capture whether or not the chain being denominated the foreign chain was the chain Truffle had deployed to. `FOREIGN_CHAIN` to my ear is just whether there is a foreign chain or not, which is always the case when the relevant tests are run. Was there a reason you didn't just end up with `HARDHAT_FOREIGN`?
* I'm not super keen on being pinned to a old version of hardhat. I tried updating (which I agree didn't work out of the box), and installed the package that was missing explicitly, and it worked, but the package that was missing was linux-specific, and we need this to work on OSX as well. Maybe a set of optional dependencies in `package.json` would make that work? It's tough to tell. But we do need to figure it out, as otherwise we'll be back where we are currently with truffle and unable to test against newer forks locally. Let's not hold this up because of it, but do it in another PR imminently.

2024-03-23 07:40 UTC, area commented
The tests        `should correctly respond to a request for a reputation state in previous states` and         `should correctly respond to a request for a reputation state in previous states with no proof` seem to have become spotty in this PR. It doesn't seem to be the case in CI, but is definitely the case locally.

Is this only for me, or do you see it as well?

2024-03-23 15:21 UTC, kronosapiens commented
@area it's pretty spotty in CI for me, re-running the build usually sorts it. I've been ignoring it for the time being.

2024-03-25 12:33 UTC, area commented
I've fixed them, though I'm not totally sold on my fix. What was happening was that when we were explicitly calling `client._miner.sync()` in those tests, the client was (sometimes) still in the process of handling blocks that it had seen, and the two sync processes would clobber each other. I'm pretty sure this is only behaviour that manifests in the tests - the miner is very gun-shy about calling `.sync` itself, and we've written it in a way that shouldn't cause this.

To resolve, I've moved the initialisation of the client out of the `beforeEach` and into the tests themselves. That means the block handler isn't active while we're doing the setup of the state we want. We then call `initialise`, which includes a `sync`. 

However, this is only treating the symptoms. I don't know why this PR cause this behaviour to manifest itself. My best guess is that the specific queries that the client is doing to sync take longer than they did with the Truffle RPC endpoint, and so by the time we hit the `sync` call on the original tests it sometimes hasn't finished. 

Are there any other newly-spotty tests you've noticed?

2024-03-25 14:30 UTC, kronosapiens commented
@area that was the only one that was consistently failing

2024-05-01 07:21 UTC, merged