Faster tests
JoinColony/colonyNetwork pull request #999
Opened 2021-11-03 22:59 UTC by kronosapiens

Speed up our test suite by removing redundant deployments & transactions.

2021-11-17 09:39 UTC, area requested changes
Why are we going back to hardcoding all the extension versions in tests?

2021-11-17 21:43 UTC, kronosapiens commented
@area fair, I dropped it since I had dropped the resolver setup. But we can easily grab it from the extension contract itself.

2022-01-28 16:30 UTC, area commented
I'm not convinced a [build with these changes](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4175/workflows/20703205-7d18-4ae8-a354-17ec61bfe025) is meaningfully faster than a [build without](https://app.circleci.com/pipelines/github/JoinColony/colonyNetwork/4170/workflows/db10e530-1df4-4452-9c14-3e340486e8a1) but we'll merge anyway.

2022-01-28 16:31 UTC, area approved these changes

2022-01-28 16:31 UTC, merged